### ISSUE TITLE
Found sample missing group field 'group'

### ISSUE THREAD

**Issue by npesc** [jacobmarks/fiftyone-albumentations-plugin#11]
Hi,

When trying out augmentations on samples that belong to a group, I stumbled upon this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fiftyone/operators/executor.py", line 277, in execute_or_delegate_operator
    result = await do_execute_operator(operator, ctx, exhaust=exhaust)
  File "/usr/local/lib/python3.10/dist-packages/fiftyone/operators/executor.py", line 319, in do_execute_operator
    result = await (
  File "/usr/local/lib/python3.10/dist-packages/fiftyone/core/utils.py", line 2343, in run_sync_task
    return await loop.run_in_executor(_get_sync_task_executor(), func, *args)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/driveblocks/fiftyone/__plugins__/@jacobmarks/albumentations_augmentation/__init__.py", line 1106, in execute
    new_sample_id = transform_sample(sample, transforms, label_fields)
  File "/home/driveblocks/fiftyone/__plugins__/@jacobmarks/albumentations_augmentation/__init__.py", line 453, in transform_sample
    sample._dataset.add_sample(new_sample)
  File "/usr/local/lib/python3.10/dist-packages/fiftyone/core/dataset.py", line 2524, in add_sample
    ids = self._add_samples_batch(
  File "/usr/local/lib/python3.10/dist-packages/fiftyone/core/dataset.py", line 2646, in _add_samples_batch
    self._validate_samples(samples)
  File "/usr/local/lib/python3.10/dist-packages/fiftyone/core/dataset.py", line 7203, in _validate_samples
    raise ValueError(
ValueError: Found sample missing group field 'group'
```

This occurs when samples have a group field and we try to augment them. I think the error is raised because the group is not ported through the augmentation and that we would be adding a sample without group to a grouped dataset. 

For this I have implemented at first, a fix that adds the group of the original sample to the augmented sample, with this the error doesn't occur anymore. However, after augmentation we can see both samples in the view but we cannot click on the augmented sample to view it separately. For this I have added a tickbox that when ticked, allows the user to "transform" the group, i.e., add a `_augmented` suffix to the group name on the augmented sample.

With this we can now augment grouped datasets and view augmented samples side by side with the original ones.

![image](https://github.com/user-attachments/assets/0d94e434-57e0-44fa-a4e7-5995241d351c)

I have tested the changes locally and made a PR for this.

Thanks

**Comment by jacobmarks** [comment]
Thanks again @npesc ! As mentioned in the PR review, there's ambiguity around group augmentations, so I'm going to close this. If you encounter any other issues or want to contribute additional functionality, I would greatly appreciate that!

**Comment by npesc** [comment]
Thanks for the feedback @jacobmarks. The bug still remains when augmenting samples in a grouped dataset context, do you have an idea how one could fix this and avoid the ambiguity?
