### ISSUE TITLE
ValueError: Key keypoint_labels is not in available keys.

### ISSUE THREAD

**Issue by darrenjkt** [jacobmarks/fiftyone-albumentations-plugin#8]
Hi Jacob, 

I've encountered an issue trying to use ZoomBlur on my object detection dataset. This same error also shows up for RandomBBoxSafeCrop.
```
▼Error occurred during operator execution

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/fiftyone/operators/executor.py", line 277, in execute_or_delegate_operator
    result = await do_execute_operator(operator, ctx, exhaust=exhaust)
  File "/usr/local/lib/python3.8/dist-packages/fiftyone/operators/executor.py", line 319, in do_execute_operator
    result = await (
  File "/usr/local/lib/python3.8/dist-packages/fiftyone/core/utils.py", line 2317, in run_sync_task
    return await loop.run_in_executor(_get_sync_task_executor(), func, *args)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/fiftyone/__plugins__/@jacobmarks/albumentations_augmentation/__init__.py", line 1100, in execute
    new_sample_id = transform_sample(sample, transforms, label_fields)
  File "/root/fiftyone/__plugins__/@jacobmarks/albumentations_augmentation/__init__.py", line 387, in transform_sample
    transformed = transform(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/albumentations/core/composition.py", line 528, in __call__
    result = super().__call__(force_apply=force_apply, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/albumentations/core/composition.py", line 247, in __call__
    self._check_args(**data)
  File "/usr/local/lib/python3.8/dist-packages/albumentations/core/composition.py", line 316, in _check_args
    raise ValueError(msg)
ValueError: Key keypoint_labels is not in available keys.
```

**Comment by jacobmarks** [comment]
Hey @darrenjkt , what version of the plugin are you using? The latest is `1.0.9`. And what version of Albumentations are you using?

**Comment by darrenjkt** [comment]
The versions are as below:

```
name: "@jacobmarks/albumentations_augmentation"
version: "1.0.9"
```

And
```
>>> albumentations.__version__
'1.4.7'
```

**Comment by jacobmarks** [comment]
Thanks @darrenjkt , looks like albumentations `1.4.7` introduced a breaking change. I've updated the plugin to be compatible with both versions :) Closing for now.
