### ISSUE TITLE
Keypoint conversion to albumentations out of bounds

### ISSUE THREAD

**Issue by npesc** [jacobmarks/fiftyone-albumentations-plugin#9]
Hi,

When experimenting with the plugin for keypoints augmentation I came across a value error, here is the full trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fiftyone/operators/executor.py", line 277, in execute_or_delegate_operator
    result = await do_execute_operator(operator, ctx, exhaust=exhaust)
  File "/usr/local/lib/python3.10/dist-packages/fiftyone/operators/executor.py", line 319, in do_execute_operator
    result = await (
  File "/usr/local/lib/python3.10/dist-packages/fiftyone/core/utils.py", line 2343, in run_sync_task
    return await loop.run_in_executor(_get_sync_task_executor(), func, *args)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/driveblocks/fiftyone/__plugins__/@jacobmarks/albumentations_augmentation/__init__.py", line 1106, in execute
    new_sample_id = transform_sample(sample, transforms, label_fields)
  File "/home/driveblocks/fiftyone/__plugins__/@jacobmarks/albumentations_augmentation/__init__.py", line 388, in transform_sample
    transformed = transform(**kwargs)
  File "/home/driveblocks/.local/lib/python3.10/site-packages/albumentations/core/composition.py", line 578, in __call__
    result = super().__call__(force_apply=force_apply, **kwargs)
  File "/home/driveblocks/.local/lib/python3.10/site-packages/albumentations/core/composition.py", line 304, in __call__
    self.preprocess(data)
  File "/home/driveblocks/.local/lib/python3.10/site-packages/albumentations/core/composition.py", line 338, in preprocess
    p.preprocess(data)
  File "/home/driveblocks/.local/lib/python3.10/site-packages/albumentations/core/utils.py", line 90, in preprocess
    data[data_name] = self.check_and_convert(data[data_name], rows, cols, direction="to")
  File "/home/driveblocks/.local/lib/python3.10/site-packages/albumentations/core/utils.py", line 104, in check_and_convert
    return self.convert_to_albumentations(data, rows, cols)
  File "/home/driveblocks/.local/lib/python3.10/site-packages/albumentations/core/keypoints_utils.py", line 130, in convert_to_albumentations
    return convert_keypoints_to_albumentations(
  File "/home/driveblocks/.local/lib/python3.10/site-packages/albumentations/core/keypoints_utils.py", line 260, in convert_keypoints_to_albumentations
    return [
  File "/home/driveblocks/.local/lib/python3.10/site-packages/albumentations/core/keypoints_utils.py", line 261, in <listcomp>
    convert_keypoint_to_albumentations(kp, source_format, rows, cols, check_validity, angle_in_degrees)
  File "/home/driveblocks/.local/lib/python3.10/site-packages/albumentations/core/keypoints_utils.py", line 214, in convert_keypoint_to_albumentations
    check_keypoint(keypoint, rows, cols)
  File "/home/driveblocks/.local/lib/python3.10/site-packages/albumentations/core/keypoints_utils.py", line 144, in check_keypoint
    raise ValueError(f"Expected {name} for keypoint {kp} to be in the range [0.0, {size}], got {value}.")
ValueError: Expected y for keypoint (3036, 2168, 0.0, 0.0, '66bca79a1cb1b8b86ba45936_2') to be in the range [0.0, 2168], got 2168.
```
The check is done in this function [github/albumentations/core/keypoints_utils.py](https://github.com/albumentations-team/albumentations/blob/39fce40c70ea2ef94579522ee81fc407c44bed95/albumentations/core/keypoints_utils.py#L140). It expects a value in the range of `[0, size of image[`.

With the current implementation [fiftyone-albumentations-plugin/utils.py](https://github.com/jacobmarks/fiftyone-albumentations-plugin/blob/1561d52b5f5607c2a1884f66975391659121e70d/utils.py#L112) it is possible that the converted value lands outside of the range, this happens when the keypoint has one coordinate that is equal to `1.0`.

To mitigate this, instead of multiplying by the size of the image, we can multiply by the size minus one.

I have forked the repo, added and tested the fix locally.

Thanks

**Comment by jacobmarks** [comment]
Thanks for logging this issue and submitting the fix :) Closing now as resolved.
